server:
  port: 8999
spring:
  redis:
#    host: 192.168.200.138
    host: 127.0.0.1
    port: 6379
    database: 3
    password:
    lettuce:
      pool:
        max-active: -1  #负数为不限制最大连接数
        max-wait: -1  #最大阻塞时间
        max-idle: 20  #最大空闲连接
        min-idle: 1
    timeout: 5000

